stages:
  - plan
  - apply
  - destroy

variables:
  TF_VERSION: "1.4.6" # Update with the desired Terraform version
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  TF_BACKEND_BUCKET: "jasuuk-state-file" # Update with your S3 bucket name
  TF_BACKEND_KEY: "kubernetes.tfstate"

before_script:
  - apt-get update -y
  - apt-get install -y unzip
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform_${TF_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform --version
  - terraform init -backend-config="bucket=${TF_BACKEND_BUCKET}" -backend-config="key=${TF_BACKEND_KEY}"

plan:
  stage: plan
  script:
    - terraform plan

apply:
  stage: apply
  script:
    - terraform apply -input=false -auto-approve
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual